### ISSUE TITLE
Truncate for "buffalo test" is not working on cockroach v2.0.6

### ISSUE THREAD

**Issue by eduDorus** [gobuffalo/buffalo#1417]
## Description

When executing "buffalo test" with a configured cockroachDB v2.0.6 the data will not get truncated after each test. The Buffalo Auth Plugin generates multiple tests to be sure the user object is not already saved in the database before testing some logic. If I execute one test it will pass, with executing the test suite most will fail. If I run the same tests on a cockroachDB v1.1.9 everything works all fine.

### Steps to Reproduce the Problem

  Please describe in painful detail what you did (so others can play along with you) to get to this point. This includes things like the exact command(s) you used, or the `curl` command you used, that sort of thing.

  1. Create a new project with "buffalo new coke --db-type cockroach"
  2. Make sure the Cockroach DB is running.
  3. Generate authentication with the buffalo auth plugin
  4. Create databases with "buffalo db create -a"
  5. Run tests("buffalo test"), some of them will fail because they expect the database to be empty. 
  6. Configure a postgre database with "buffalo db g config"
  7. Create databases with "buffalo db create -a"
  8. Run tests("buffalo test"), the tests pass all

### Expected Behavior

After each test the cockroach database should truncate the created rows.

### Actual Behavior

After each test the cockroach database keeps the data.

### Info

<details>

```
### Buffalo Version
v0.13.2

### App Information
Pwd=/Users/dorus/go/src/github.com/edudorus/asom
Root=/Users/dorus/go/src/github.com/edudorus/asom
GoPath=/Users/dorus/go
Name=asom
Bin=bin/asom
PackagePkg=github.com/edudorus/asom
ActionsPkg=github.com/edudorus/asom/actions
ModelsPkg=github.com/edudorus/asom/models
GriftsPkg=github.com/edudorus/asom/grifts
VCS=git
WithPop=true
WithSQLite=false
WithDep=false
WithWebpack=true
WithYarn=false
WithDocker=true
WithGrifts=true
WithModules=false

### Go Version
go version go1.11.1 darwin/amd64

### Go Env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/dorus/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/dorus/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.11.1/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.11.1/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/_5/7c3lr50s2wzgmw_y31t1r6400000gn/T/go-build684181983=/tmp/go-build -gno-record-gcc-switches -fno-common"

### Node Version
v11.0.0

### NPM Version
6.4.1

### Yarn Version
Yarn Not Found

### PostgreSQL Version
pg_ctl (PostgreSQL) 10.5

### MySQL Version
mysql  Ver 8.0.12 for osx10.14 on x86_64 (Homebrew)

### SQLite Version
3.24.0 2018-06-04 14:10:15 95fbac39baaab1c3a84fdfc82ccb7f42398b2e92f18a2a57bce1d4a713cbaapl

### Dep Version
could not find a Gopkg.toml file

### Dep Status
could not find a Gopkg.toml file

### go.mod
module github.com/edudorus/asom
```

</details>

**Comment by eduDorus** [comment]
Reboot all my systems and probably there was something corrupt with my cockroachDB. Sorry for the troubles and thanks for developing buffalo!

**Comment by eduDorus** [comment]
It seems the problem exists with cockroach 2.0.6. Everything works fine with cockroach 1.1.9

**Comment by sio4** [comment]
What are your `pop` version and your `database.yml`?
Current `master` branch of `pop` does not support cockroach URL well, and the fix for it already merged into `development` branch of `pop`. Anyway, since it still not merged into `master`, you can try with `development` branch.

@markbates, @stanislas-m, is there any timeline to merge that codes into `master`? the latest release does not include that changes.

**Comment by eduDorus** [comment]
@sio4 thank you for the fast response. My pop version is v4.8.5 and my database.yml is generated with "buffalo pop g config -t cockroach". Yesterday I did some further testing and it seems that all works fine with Postgres.

```yml
development:
  dialect: cockroach
  database: asom_development
  host: {{envOr "COCKROACH_HOST" "127.0.0.1"  }}
  port: {{ envOr "COCKROACH_PORT" "26257"  }}
  user: {{ envOr "COCKROACH_USER" "root"  }}
  password: {{ envOr "COCKROACH_PASSWORD" ""  }}
  pool: 5

test:
  dialect: cockroach
  database: asom_test
  host: {{ envOr "COCKROACH_HOST" "127.0.0.1"  }}
  port: {{ envOr "COCKROACH_PORT" "26257"  }}
  user: {{ envOr "COCKROACH_USER" "root"  }}
  password: {{ envOr "COCKROACH_PASSWORD" ""  }}
  pool: 5

production:
  dialect: cockroach
  database: asom_production
  host: {{ envOr "COCKROACH_HOST" "127.0.0.1"  }}
  port: {{ envOr "COCKROACH_PORT" "26257"  }}
  user: {{ envOr "COCKROACH_USER" "root"  }}
  password: {{ envOr "COCKROACH_PASSWORD" ""  }}
  pool: 5
```
