### ISSUE TITLE
Proposal: Read databases password from environment variables

### ISSUE THREAD

**Issue by microboym** [gobuffalo/buffalo#1640]
Is there any way to read my database password from environment variables?

I added `DATABASE_PASSWORD=XXXXXXXXX` to the end of **.env** file.
But I want to know how to read it using pop.

I tried this
**database.yml**:
```yml
development:
  dialect: postgres
  database: postgres
  user: postgres
  password: $DATABASE_PASSWORD
  host: 127.0.0.1
  pool: 5
```
But `pop.Connections["development"].String()` returns `"postgres://postgres:$DATABASE_PASSWORD@127.0.0.1/postgres"`
