### ISSUE TITLE
Generating invalid .codeclimate.yml

### ISSUE THREAD

**Issue by amedeiros** [gobuffalo/buffalo#173]
Buffalo version 0.7.1

Step 1 install codeclimate cli

`brew tap codeclimate/formulae`
`brew install codeclimate`

Step 2 create new buffalo project

`buffalo new coke`

Step 3 run validate-config with codeclimate cli from new project root.

`codeclimate validate-config`

Result:

`ERROR: syntax error: (<unknown>): did not find expected key while parsing a block mapping at line 1 column 1`

Solution run `nCodeClimate` through a yaml linter.

```
const nCodeClimate = `engines:
  fixme:
    enabled: true
  gofmt:
    enabled: true
  golint:
    enabled: true
  govet:
    enabled: true
exclude_paths:
  - grifts/**/*
  - "**/*_test.go"
  - "*_test.go"
  - "**_test.go"
  - logs/*
  - public/*
  - templates/*
ratings:
  paths:
    - "**.go"

`
```

Run `codeclimate validate-config` again

`No errors or warnings found in .codeclimate.yml file.`

I can open a pull request for this are there an specific contribution guides I should look at first?
