### ISSUE TITLE
Update codeclimate.yml

### ISSUE THREAD

**Issue by boskiv** [gobuffalo/buffalo#1903]
Hello! Thank you so much for your interest in Buffalo. The fact you care enough to be here, right now, helping, makes us very happy.
### Description

There is a new version of codeclimate config
https://docs.codeclimate.com/docs/advanced-configuration#section-examples

Please update it in new project templates.
Also please add node_modules to exclude_patterns

This is my example
```
version: "2"
checks:
  method-lines:
    config:
      threshold: 100
plugins:
  fixme:
    enabled: true
  gofmt:
    enabled: true
  golint:
    enabled: true
  govet:
    enabled: true
exclude_patterns:
  - grifts/**/*
  - "**/*_test.go"
  - "*_test.go"
  - "**_test.go"
  - logs/*
  - public/*
  - templates/*
  - "**/node_modules/"
```
