### ISSUE TITLE
Wrong sqlite3 path: buffalo db create puts the database file into wrong directory

### ISSUE THREAD

**Issue by as27** [gobuffalo/buffalo#436]
After my HD crash I could reproduce this with a complete fresh Buffalo 0.8.2 installation.

I don't know if this issue should be under the `pop` repository or if Buffalo just generates a wrong base path.

So how to reproduce the bug:

1.  I created a new folder under `GOPATH/src/` named `buffalotest`
2. Changed to the new folder and create a new project `buffalo new coke --db-type sqlite3`
3. Create the db `buffalo db create`

The sqlite file is not under the project folder `GOPATH/src/buffalotest/coke/`. Instead of putting the file inside the project folder buffalo created a new folder `GOPATH/buffalotest/coke/`

Inside the `database.yaml` the path is wrong generated:

```yaml
development:
  dialect: "sqlite3"
  database: {{env "GOPATH" }}/buffalotest/coke/coke_development.sqlite

test:
  dialect: "sqlite3"
  database: {{env "GOPATH" }}/buffalotest/coke/coke_test.sqlite

production:
  dialect: "sqlite3"
  database: {{env "GOPATH" }}/buffalotest/coke/coke_production.sqlite
```

While running buffalo new the `src` folder has to be included to the paths.
