### ISSUE TITLE
Automate Windows Testing

### ISSUE THREAD

**Issue by paganotoni** [gobuffalo/buffalo#522]
Some of the issues we've been receiving on Buffalo are related with Windows, that is because typically contributors use Linux/MacOS machines to develop and our CI runs a Docker image that is another Linux machine.

It is important to provide a more stable experience to our Windows users that allow them to engage with buffalo as well as build new applications using the Ecosystem, otherwise new-coming Windows users will leave buffalo even before start.

Before 1.0.0 we should make sure we have some automated Windows testing that allows us to ensure a better experience for new Windows users as well as Unix users moving to Windows.

**Comment by apaganobeleno** [comment]
I just did a quick search and one of the things we could do is implement https://www.appveyor.com/ inside our repo.

**Comment by stanislas-m** [comment]
@paganotoni @markbates Here is a starting point using appveyor:

```yaml
version: '{build}'

image: Visual Studio 2017

clone_depth: 5

clone_folder: c:\gopath\src\github.com\gobuffalo\buffalo

environment:
  GOPATH: c:\gopath

services:
- mysql
- postgresql

install:
- cmd: >-
    choco install mingw
    set PATH=%GOPATH%\bin;c:\go\bin;c:\tools\mingw64\bin;%PATH%
    echo %PATH%
    echo %GOPATH%
    go version
    go env

build_script:
- cmd: go get -v -t ./...

test_script:
- cmd: for /f "" %%G in ('go list github.com/gobuffalo/buffalo/... ^| find /i /v "/vendor/"') do ( go test %%G & IF ERRORLEVEL == 1 EXIT 1)
```
