### ISSUE TITLE
Gitlab ci fails with a new project

### ISSUE THREAD

**Issue by alexcarol** [gobuffalo/buffalo#575]
Steps to reproduce:
- create a new project with: buffalo new test -f --api --ci-provider gitlab-ci -v
- push to gitlab
- check how gitlab-ci job fails

I also tried with mysql and I got an error as well.

https://gitlab.com/alexcarol/test
Latest:
- https://gitlab.com/alexcarol/test/-/jobs/27033773
- ```Error: error creating PostgreSQL database test_test: exec: "createdb": executable file not found in $PATH```

1.7:
- https://gitlab.com/alexcarol/test/-/jobs/27033776
fails probably because  gobuffalo does not even support this version

I came across this issue when trying to move an existing project to gitlab.

Thanks for your help.

**Comment by markbates** [comment]
You are missing the Postgres dev tools. Buffalo uses them to do things like create a database, dump schemas, etc…

**Comment by alexcarol** [comment]
Shouldn't the autogenerated .gitlab-ci.yml provide them out of the box?
I tried using the latest gobuffalo docker image instead (as it looks like it has the needed tools) and got a different error: https://gitlab.com/alexcarol/test/-/jobs/27044692

Thanks for your help.

**Comment by markbates** [comment]
Personally I don't really know anything about gitlab CI so I'm not much of a help I'm afraid. To answer the first question, it probably should install the tools needed for the different databases. Again, I don't use it so if you figure it out, a PR would be very appreciated.

As for using the docker image all the tools are installed in the images, but database servers are not started. You are expected to configure and connect the database of your choice.

-----------
Mark Bates

**Comment by markbates** [comment]
I would recommend joining the #buffalo slack channel on gophers.slack.com see if anyone there has experience with gitlab, see if they can help.

-----------
Mark Bates

**Comment by baldrailers** [comment]
There's a documentation listed [here](https://docs.gitlab.com/ce/ci/services/postgres.html).

**Comment by stanislas-m** [comment]
I wrote the original Gitlab CI adapter, I'll take a look after my work. :)

**Comment by baldrailers** [comment]
It works nicely if you are not using `postgresql`, with `0.9.2` generator defaults to `sqlite` it'll work seamlessly. I "think" the problem is the container links as per `command not found` with `createdb`.

**Comment by stanislas-m** [comment]
I tested it a bit to fix the Gitlab CI generator:

```yaml
before_script:
  - apt-get update && apt-get install -y postgresql-client mysql-client
  - ln -s /builds /go/src/$(echo "gitlab.com/stanislas-m/test" | cut -d "/" -f1)
  - cd /go/src/gitlab.com/stanislas-m/test
  - mkdir -p public/assets
  - go get -u github.com/gobuffalo/buffalo/buffalo
  - go get -t -v ./...
  - export PATH="$PATH:$GOPATH/bin"

stages:
  - test

.test-vars: &test-vars
  variables:
    GO_ENV: "test"
    POSTGRES_DB: "test_test"
    MYSQL_DATABASE: "test_test"
    MYSQL_ROOT_PASSWORD: "root"
    TEST_DATABASE_URL: "postgres://postgres:postgres@postgres:5432/test_test"

# Golang version choice helper
.use-golang-image: &use-golang-latest
  image: golang:latest

.use-golang-image: &use-golang-1-8
  image: golang:1.8

test:latest:
  <<: *use-golang-latest
  <<: *test-vars
  stage: test
  services:
    - mysql:latest
    - postgres:latest
  script:
    - buffalo test

test:1.8:
  <<: *use-golang-1-8
  <<: *test-vars
  stage: test
  services:
    - mysql:latest
    - postgres:latest
  script:
    - buffalo test
```

When I run the CI, I still have an error: the test command seems trying to dump the dev schema:

``` bash
$ buffalo test
Buffalo version v0.9.2

dropped database test_test
created database test_test
pg_dump: [archiver (db)] connection to database "test_development" failed: could not connect to server: Connection refused
	Is the server running on host "127.0.0.1" and accepting
	TCP/IP connections on port 5432?
```

**Comment by stanislas-m** [comment]
Even with this dump problem, I made it work by disabling the ssl mode:

```yaml
before_script:
  - apt-get update && apt-get install -y postgresql-client mysql-client
  - ln -s /builds /go/src/$(echo "gitlab.com/stanislas-m/test" | cut -d "/" -f1)
  - cd /go/src/gitlab.com/stanislas-m/test
  - mkdir -p public/assets
  - go get -u github.com/gobuffalo/buffalo/buffalo
  - go get -t -v ./...
  - export PATH="$PATH:$GOPATH/bin"

stages:
  - test

.test-vars: &test-vars
  variables:
    GO_ENV: "test"
    POSTGRES_DB: "test_test"
    MYSQL_DATABASE: "test_test"
    MYSQL_ROOT_PASSWORD: "root"
    TEST_DATABASE_URL: "postgres://postgres:postgres@postgres:5432/test_test?sslmode=disable"

# Golang version choice helper
.use-golang-image: &use-golang-latest
  image: golang:latest

.use-golang-image: &use-golang-1-8
  image: golang:1.8

test:latest:
  <<: *use-golang-latest
  <<: *test-vars
  stage: test
  services:
    - mysql:latest
    - postgres:latest
  script:
    - buffalo test

test:1.8:
  <<: *use-golang-1-8
  <<: *test-vars
  stage: test
  services:
    - mysql:latest
    - postgres:latest
  script:
    - buffalo test
```

**Comment by stanislas-m** [comment]
@alexcarol, is this one fixed?

**Comment by bryanstephens** [comment]
May or may not be related to the issue @alexcarol is seeing but I generated my project to use MySQL and saw a different error on gitlab-ci:

```
$ buffalo test
Error: Could not find connection named test!

Usage:
  buffalo test [flags]

Flags:
  -h, --help   help for test

ERROR: Job failed: exit code 1
```

I pushed up a changes to the scripts multiple times to see if I could find out more info until I finally ended up with the following:

```
$ go test ./... -v
?   	gitlab.com/bryanstephens/go-buffalo-banking	[no test files]
2017/11/07 05:55:07 The URL is not supported by MySQL driver.
FAIL	gitlab.com/bryanstephens/go-buffalo-banking/actions	0.027s
?   	gitlab.com/bryanstephens/go-buffalo-banking/grifts	[no test files]
2017/11/07 05:55:07 Could not find connection named test!
FAIL	gitlab.com/bryanstephens/go-buffalo-banking/models	0.008s
ERROR: Job failed: exit code 1
```

Turns out the url in the `.gitlab-ci.yml` file does not work with the MySQL option. My new `.gitlab-ci.yml` file looks like the following and passes now (note the parenthesis around the host/port):

```
before_script:
  - apt-get update && apt-get install -y mysql-client
  - ln -s /builds /go/src/$(echo "gitlab.com/bryanstephens/go-buffalo-banking" | cut -d "/" -f1)
  - cd /go/src/gitlab.com/bryanstephens/go-buffalo-banking
  - mkdir -p public/assets
  - go get -u github.com/gobuffalo/buffalo/buffalo
  - go get -t -v ./...
  - export PATH="$PATH:$GOPATH/bin"

stages:
  - test

.test-vars: &test-vars
  variables:
    GO_ENV: "test"
    MYSQL_DATABASE: "go-buffalo-banking_test"
    MYSQL_ROOT_PASSWORD: "root"
    TEST_DATABASE_URL: "mysql://root:root@(mysql:3306)/go-buffalo-banking_test"

.use-golang-image: &use-golang-1-8
  image: golang:1.8

test:1.8:
  <<: *use-golang-1-8
  <<: *test-vars
  stage: test
  services:
    - mysql:5.7
  script:
    - buffalo test
```
