### ISSUE TITLE
Create / drop database not working

### ISSUE THREAD

**Issue by Ibrahimous** [gobuffalo/buffalo#836]
Hi there,

Thanks for your work, at first :)
I ran into problems just executing the following command:
`$ buffalo create db -a`
OR

`$ buffalo db drop -a`

I have the following database.yml:

```
development:
  dialect: postgres
  database: myAppdb
  user: user
  password: password
  host: 127.0.0.1
  pool: 5

test:
  url: {{envOr "TEST_DATABASE_URL" "postgres://user:password@127.0.0.1:5432/myApp_test?sslmode=disable"}}

production:
  url: {{envOr "DATABASE_URL" "postgres://user:password@127.0.0.1:5432/myApp_production?sslmode=disable"}}
```

I get:

```
$ buffalo db drop -a
v3.41.3

couldn't drop database myApp_test: error dropping PostgreSQL database myApp_test: pq: authentification par mot de passe échouée pour l'utilisateur  « user »
couldn't drop database myApp_production: error dropping PostgreSQL database myApp_production: pq: authentification par mot de passe échouée pour l'utilisateur  « user »
couldn't drop database myAppdb: error dropping PostgreSQL database myAppdb: pq: la base de données « user » n'existe pas
```

Meaning: buffalo seems to understand postgres://user:password as postgres://DATABASEr:password !

Any help, please ?
