### ISSUE TITLE
Migrations are not running

### ISSUE THREAD

**Issue by nithin-bose** [gobuffalo/buffalo#906]
I have noticed that migrations are not when triggered with ``app migrate`` command from the container created from the docker file generated by Buffalo. It just shows the following:

```
bash-4.4# app migrate

0.0061 seconds

```
Checking the db shows shows that the ``schema_migrations`` table has been created with no rows. 
The same happens for both ``sql`` and ``fizz`` migrations. It works fine when run on the local machine. Issue happens only when migrations are run from the container.

Am i missing something?

**Comment by nithin-bose** [comment]
Is there a way to see debug messages??

**Comment by markbates** [comment]
Can you give more information about your setup? What database are you using? What does your Dockerfile look like? Your database.yml?

**Comment by nithin-bose** [comment]
I am using postgres with the following database.yml:
```yaml
development:
  dialect: postgres
  database: development
  user: postgres
  password: postgres
  host: 127.0.0.1
  port: 5432
  pool: 5

test:
  dialect: postgres
  database: {{env "DB_DATABASE"}}
  user: {{env "DB_USER"}}
  password: {{env "DB_PASSWD"}}
  host: {{env "DB_HOST"}}
  port: {{env "DB_PORT"}}
  pool: {{env "DB_POOL"}}

production:
  dialect: postgres
  database: {{env "DB_DATABASE"}}
  user: {{env "DB_USER"}}
  password: {{env "DB_PASSWD"}}
  host: {{env "DB_HOST"}}
  port: {{env "DB_PORT"}}
  pool: {{env "DB_POOL"}}
```
Migrations does parse env variables right??
