### ISSUE TITLE
[question] Test database session store

### ISSUE THREAD

**Issue by danikarik** [gobuffalo/buffalo#917]
I have session store which use POP to create/update data in database.

Function App looks like:
```
func App() *buffalo.App {
	if app == nil {
		app = buffalo.New(buffalo.Options{
			Env:          ENV,
			SessionStore: store.NewPopStore(models.DB, []byte(SECRET)),
			SessionName:  "sessionid",
		})
...
```

Login/logout works fine. But when I run tests, getting error message:
```
level=debug msg="select table_name from information_schema.tables;"
--- FAIL: Test_ActionSuite (0.02s)
    --- FAIL: Test_ActionSuite/Test_Auth_Login (0.01s)
        Error Trace:    model.go:20
    	            	suite.go:47
    	            	suite.go:88
    	Error:      	Received unexpected error:
    	            	missing destination name table_name in *[]pop.table
```

Test:

```
func (as *ActionSuite) Test_Auth_Login() {
	...
	resp := as.JSON("/session").Post(data)
	apiResp := &APIResponse{}
	resp.Bind(apiResp)
	as.Equal(200, resp.Code)
	as.Equal(SUCCESS, apiResp.Status)
        ...
}
```

**Is it correct?**

**Comment by danikarik** [comment]
Error raised here:

```
func (p *cockroach) TruncateAll(tx *Connection) error {
	type table struct {
		TableName string `sql:"table_name"`
	}

	tables := []table{}
	if err := tx.RawQuery("select table_name from information_schema.tables;").All(&tables); err != nil {
                // HERE <<<<
		return err
	}

	table_names := make([]string, len(tables))
	for i, t := range tables {
		table_names[i] = t.TableName
	}

	return tx.RawQuery(fmt.Sprintf("truncate %s cascade;", strings.Join(table_names, ", "))).Exec()
}
```

database.yml:

```
development:
  dialect: cockroach
  database: {{ envOr "COCKROACH_DATABASE" "carbase"  }}
  host: {{ envOr "COCKROACH_HOST" "127.0.0.1"  }}
  port: {{ envOr "COCKROACH_PORT" "26257"  }}
  user: {{ envOr "COCKROACH_USER" "carthage"  }}
  password: {{ envOr "COCKROACH_PASSWORD" "dthcnf07"  }}
  pool: {{ envOr "COCKROACH_POOL" "5"  }}
  options:
    sslmode: {{ envOr "COCKROACH_SSLMODE" "disable"  }}

test:
  dialect: cockroach
  database: {{ envOr "COCKROACH_DATABASE" "testdb"  }}
  host: {{ envOr "COCKROACH_HOST" "127.0.0.1"  }}
  port: {{ envOr "COCKROACH_PORT" "26257"  }}
  user: {{ envOr "COCKROACH_USER" "testusr"  }}
  password: {{ envOr "COCKROACH_PASSWORD" "testpwd"  }}
  pool: {{ envOr "COCKROACH_POOL" "5"  }}
  options:
    sslmode: {{ envOr "COCKROACH_SSLMODE" "disable"  }}
```
