### ISSUE TITLE
Docker-compose generator

### ISSUE THREAD

**Issue by stanislas-m** [gobuffalo/buffalo#928]
Since Buffalo already generates a Docker file, it can be a great addition to generate a docker-compose.yml file too.

This file will be generated from the DB params provided to the `new` command.

Here is a raw template for a postgres version (just an idea, not the final thing):

```
version: '3'

services:
  db:
    container_name: {{ .opts.Name.Title }}-db
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: {{ .opts.Name.Title }}_${GO_ENV:-development}
    volumes:
      - ./db:/var/lib/postgresql/data
```

**Comment by markbates** [comment]
more color:

What I would love would be a generator, or a flag on new, that sets up docker compose with the app and one of the support dbs all configured to work together out of the box. That would be really nice.

Then buffalo dev could check for all that and start it up and run the app locally in the docker container.

**Comment by gintsgints** [comment]
We would need script like this:

```
until nc -z ${MYSQL_HOST} ${MYSQL_PORT}; do
    echo "$(date) - waiting for mysql..."
    sleep 1
done
```
In docker image. For that to make, how about to move helper docker image sources out to different project?

**Comment by gintsgints** [comment]
I made docker image with script included gintsgints/docker-buffalo , but sadly when I do 

```
buffalo dev
```
with generated app inside that container, it stacks after font-awesome.

**Comment by gintsgints** [comment]
Got it working for dev environment. So, bit updated Dockerfile (based on my modified image & put ADDR env variable also for builder build. Begining:

```
# This is a multi-stage Dockerfile and requires >= Docker 17.05
# https://docs.docker.com/engine/userguide/eng-image/multistage-build/
FROM gintsgints/docker-buffalo as builder

RUN mkdir -p $GOPATH/src/gitlab.com/gintsgints/coke
WORKDIR $GOPATH/src/gitlab.com/gintsgints/coke

# this will cache the npm install step, unless package.json changes
ADD package.json .
ADD yarn.lock .
RUN yarn install --no-progress
ADD . .
RUN go get $(go list ./... | grep -v /vendor/)
RUN buffalo build --static -o /bin/app

# Bind the app to 0.0.0.0 so it can be seen from outside the container
ENV ADDR=0.0.0.0
```

And compose file as follows:

```
version: '3.5'
services:
  app:
    build:
      context: .
      target: builder
    depends_on:
    - db
    ports:
    - "3000:3000"
    volumes:
    - .:/go/src/gitlab.com/gintsgints/coke
    working_dir: /go/src/gitlab.com/gintsgints/coke
    command: bash -c "/wait-for db:3306 && buffalo db migrate && buffalo dev"
    networks:
      - appnet
  db:
    image: mysql:5.7.17
    environment:
    - MYSQL_ROOT_PASSWORD=root_234
    - MYSQL_DATABASE=coke_development
    networks:
      - appnet
networks:
  appnet:
```

After this you can start environment by executing:

```
docker-compose -f docker-compose.dev.yml build
docker-compose -f docker-compose.dev.yml up -d
```
